# Site settings
title: George Prichard's blog
email: dgmprichard@gmail.com
description: "The blog of George Prichard."
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
